// <auto-generated />
using System;
using DartPerformanceTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DartPerformanceTracker.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260228203036_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DartPerformanceTracker.Shared.Models.GameNight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHome")
                        .HasColumnType("bit");

                    b.Property<string>("Opponent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("GameNights");
                });

            modelBuilder.Entity("DartPerformanceTracker.Shared.Models.ManOfTheMatch", b =>
                {
                    b.Property<int>("GameNightId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("GameNightId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("ManOfTheMatches");
                });

            modelBuilder.Entity("DartPerformanceTracker.Shared.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameNightId")
                        .HasColumnType("int");

                    b.Property<int>("LegsLost")
                        .HasColumnType("int");

                    b.Property<int>("LegsWon")
                        .HasColumnType("int");

                    b.Property<int>("MatchTypeId")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<bool>("Won")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GameNightId");

                    b.HasIndex("MatchTypeId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("DartPerformanceTracker.Shared.Models.MatchPlayer", b =>
                {
                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("MatchId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("MatchPlayers");
                });

            modelBuilder.Entity("DartPerformanceTracker.Shared.Models.MatchType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayersPerSide")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MatchTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Singles",
                            PlayersPerSide = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pairs",
                            PlayersPerSide = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Triples",
                            PlayersPerSide = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fours",
                            PlayersPerSide = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sixes",
                            PlayersPerSide = 6
                        },
                        new
                        {
                            Id = 6,
                            Name = "Blind Pairs",
                            PlayersPerSide = 2
                        });
                });

            modelBuilder.Entity("DartPerformanceTracker.Shared.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("DartPerformanceTracker.Shared.Models.PlayerMatchStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("Maximums")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Tons")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerMatchStats");
                });

            modelBuilder.Entity("DartPerformanceTracker.Shared.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaximumScore")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("DartPerformanceTracker.Shared.Models.SeasonMatchConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MatchTypeId")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchTypeId");

                    b.HasIndex("SeasonId");

                    b.ToTable("SeasonMatchConfigurations");
                });

            modelBuilder.Entity("DartPerformanceTracker.Shared.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("DartPerformanceTracker.Shared.Models.GameNight", b =>
                {
                    b.HasOne("DartPerformanceTracker.Shared.Models.Season", "Season")
                        .WithMany("GameNights")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("DartPerformanceTracker.Shared.Models.ManOfTheMatch", b =>
                {
                    b.HasOne("DartPerformanceTracker.Shared.Models.GameNight", "GameNight")
                        .WithMany("ManOfTheMatchAwards")
                        .HasForeignKey("GameNightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DartPerformanceTracker.Shared.Models.Player", "Player")
                        .WithMany("ManOfTheMatchAwards")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameNight");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DartPerformanceTracker.Shared.Models.Match", b =>
                {
                    b.HasOne("DartPerformanceTracker.Shared.Models.GameNight", "GameNight")
                        .WithMany("Matches")
                        .HasForeignKey("GameNightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DartPerformanceTracker.Shared.Models.MatchType", "MatchType")
                        .WithMany("Matches")
                        .HasForeignKey("MatchTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameNight");

                    b.Navigation("MatchType");
                });

            modelBuilder.Entity("DartPerformanceTracker.Shared.Models.MatchPlayer", b =>
                {
                    b.HasOne("DartPerformanceTracker.Shared.Models.Match", "Match")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DartPerformanceTracker.Shared.Models.Player", "Player")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DartPerformanceTracker.Shared.Models.Player", b =>
                {
                    b.HasOne("DartPerformanceTracker.Shared.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("DartPerformanceTracker.Shared.Models.PlayerMatchStats", b =>
                {
                    b.HasOne("DartPerformanceTracker.Shared.Models.Match", "Match")
                        .WithMany("PlayerStats")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DartPerformanceTracker.Shared.Models.Player", "Player")
                        .WithMany("Stats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DartPerformanceTracker.Shared.Models.SeasonMatchConfiguration", b =>
                {
                    b.HasOne("DartPerformanceTracker.Shared.Models.MatchType", "MatchType")
                        .WithMany("SeasonConfigurations")
                        .HasForeignKey("MatchTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DartPerformanceTracker.Shared.Models.Season", "Season")
                        .WithMany("MatchConfigurations")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchType");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("DartPerformanceTracker.Shared.Models.GameNight", b =>
                {
                    b.Navigation("ManOfTheMatchAwards");

                    b.Navigation("Matches");
                });

            modelBuilder.Entity("DartPerformanceTracker.Shared.Models.Match", b =>
                {
                    b.Navigation("MatchPlayers");

                    b.Navigation("PlayerStats");
                });

            modelBuilder.Entity("DartPerformanceTracker.Shared.Models.MatchType", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("SeasonConfigurations");
                });

            modelBuilder.Entity("DartPerformanceTracker.Shared.Models.Player", b =>
                {
                    b.Navigation("ManOfTheMatchAwards");

                    b.Navigation("MatchPlayers");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("DartPerformanceTracker.Shared.Models.Season", b =>
                {
                    b.Navigation("GameNights");

                    b.Navigation("MatchConfigurations");
                });

            modelBuilder.Entity("DartPerformanceTracker.Shared.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
